version: 2.0

jobs:
    build:
        docker:
            - image: circleci/openjdk:8-stretch-node-browsers 
        steps:
            - checkout
            - restore_cache:
                keys:
                    - gradle-{{ checksum "build.gradle" }}
            - run: sudo apt-get update && sudo apt-get install autoconf && sudo apt-get install cmake
            - run: ./gradlew build
            - save_cache:
                paths:
                    - ~/.gradle
                key: gradle-{{ checksum "build.gradle" }}
            - store_artifacts:
                path: build/distributions
                destination: distributions
            - store_artifacts:
                path: build/libs
                destination: libs
